[package]
name = "coreutils"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
eyre.workspace = true
rustix = { version = "0.38.37", features = ["process"] }
